### PR TITLE
Added Audio Component.

### PR DESCRIPTION
**Pull request by IngaleChinmay04**
Added customizable audio player component with play, volume, and progress controls.

Closses Issue: #15 

https://github.com/user-attachments/assets/af233ec2-aeb0-4115-9906-adf953ecfd8f

### CODE REVIEW

**Comment by gautamankoji** [comment]
@IngaleChinmay04
please try to make it more minimalist and modern by compacting the controls into an icon with a dropdown for customization
if you fulfill these requirements, your PR will be merged

**Comment by IngaleChinmay04** [comment]
Updated the component!


https://github.com/user-attachments/assets/7a830c5e-b328-4bce-8577-0c4f7dfd1ad1

**Comment by gautamankoji** [comment]
good job @IngaleChinmay04!
next time, focus on improving your styling and keep contributing to open source, if you're still interested, you can either work on other issues or create new ones if you have any feature requests

kudos again for contributing!

**Comment by IngaleChinmay04** [comment]
Thank you @gautamankoji! Sure I will contribute.

**Pull request merged**
